### ISSUE TITLE
[RFC] Introduction and request to contribute

### ISSUE THREAD

**Issue by hugomn** [stardust-ui/react-old#12]
## Contribution Request

Hello! I'm with the @infinitecsolutions Front-End team, and we are actively using [SUIR](https://github.com/Semantic-Org/Semantic-UI-React) v0.8. We are now building our company UI library and we plan to have [SUIR](https://github.com/Semantic-Org/Semantic-UI-React) as our base. 
We currently have 3 full-time developers focused on building a reusable library and to contribute to [SUIR](https://github.com/Semantic-Org/Semantic-UI-React). 

I took my time yesterday to understand about Stardust and the plans for [SUIR](https://github.com/Semantic-Org/Semantic-UI-React) v1 and v2 and I'm quite impressed with the plan. It's totally according to our future plans and I truly believe we can help somehow. 

In order not to go too long, I want to understand the process of proposing new behaviors inside Semantic-UI and how will Stardust handle them. For example, we have an internal requirement that our multiple selection dropdowns should not display labels, but checkbox instead (we already have an implementation of it in  [SUIR](https://github.com/Semantic-Org/Semantic-UI-React) v0.8). 

Last but not least, I'm really happy to see this amazing movement here towards a consistency in UI components on the web. Thank you all, specially @levithomason for this amazing work. 👏🏻

**Comment by levithomason** [comment]
Hi @hugomn, thanks for posting.  We'd love to have your teams' input and help.

I will be updating the CONTRIBUTING.md to walk folks through the process of contributing to v2 and Stardust.  In the meantime, you can post any ideas here in the Stardust fork.

Please post a [new feature request](https://github.com/levithomason/stardust/issues/new?template=Feature_request.md).  We'd love to collaboratively work through the API and solution with your team.  We have many thoughts on the Dropdown moving forward as well.

**Comment by hugomn** [comment]
Thanks, @levithomason. I'll for sure do that. I'm currently implementing our Multiple Selection dropdown with checkboxes in a fork of SUIR. Do you think it's a good approach to create the new feature request and to make it a candidate for a PR in SUIR v0.8? How should we proceed?

**Comment by levithomason** [comment]
Posting a proposal here would be great. The Dropdown in v1 is unlikely to receive large updates.

**Comment by hugomn** [comment]
Perfect, will do that. Thanks!
