### ISSUE TITLE
feat: add Menu Icons variation

### ISSUE THREAD

**Issue by alinais** [stardust-ui/react-old#121]
## API Proposal
This API extends the Menu component

### icon
![image](https://user-images.githubusercontent.com/1826985/42947738-40576d1c-8b6e-11e8-8c66-43bff83a6b60.png)

```
  <Menu icon>
      <Menu.Item name='gamepad' active={activeItem === 'gamepad'} onClick={this.handleItemClick}>
          <Icon name='gamepad' />
      </Menu.Item>

      <Menu.Item
          name='video camera'
          active={activeItem === 'video camera'}
          onClick={this.handleItemClick}
      >
          <Icon name='video camera' />
      </Menu.Item>

      <Menu.Item
          name='video play'
          active={activeItem === 'video play'}
          onClick={this.handleItemClick}
      >
          <Icon name='video play' />
      </Menu.Item>
  </Menu>

```

**Comment by levithomason** [comment]
Note, our use cases for the icon menu should be styled a bit differently.  There is no background, shadows, or borders:

![image](https://user-images.githubusercontent.com/5067638/43007764-29621672-8bee-11e8-99ec-3c6e2e9aea11.png)

In this case, a background color matching the message is applied to the menu to occlude the timestamp:

![image](https://user-images.githubusercontent.com/5067638/43008302-85e5296a-8bef-11e8-857a-6f2f9dd69b7b.png)

![image](https://user-images.githubusercontent.com/5067638/43008309-8df66ace-8bef-11e8-9370-24a48e9246e0.png)

Also with a white background:

![image](https://user-images.githubusercontent.com/5067638/43008507-1fa6b280-8bf0-11e8-966e-efcbd578007a.png)

![image](https://user-images.githubusercontent.com/5067638/43008520-2753af2e-8bf0-11e8-880a-f33c783da988.png)

There was some discussion in the Icon component about adding a `background` prop to handle these kind of cases.  See #86.  We could either allow the icons in the screenshots above to take on a background color, or pass it through the Menu.

For now, we may just leave the background color out of the equation.  This could be something that we introduce by allowing components to take on colors from their context.  So, the Menu might be able to take on the background of the surrounding context, which is the Message component.

**Comment by kuzhelov** [comment]
what I do see as a solution here is to allow merged `variables` to be consumed inside `renderComponent()` method. Currently we are passing, essentially, only class names there (if we would speak about visual aspects). With that this problem seems to be easily solvable:

```jsx
class ChatMessage extends UIComponent {
   ... 
   // note that 'variables' are merged ones
   renderComponent({ classNames, variables } => (
     <Menu variables={background: variables.background}>
     ...
    </Menu>
  ))
}
```

This mechanism is explicit, easy to debug and, to my mind, is able to accomplish the tasks you've mentioned.

@levithomason, @alinais, please, let me know what do you think?

**Comment by miroslavstastny** [comment]
Done in stardust-ui/react/pull/73
