### ISSUE TITLE
Docs URL no longer working after repo rename.

### ISSUE THREAD

**Issue by brianespinosa** [stardust-ui/react-old#76]
### Steps
Visit http://stardust-ui.github.io/stardust as defined at the top of the repo description.

### Expected Result
You can see the current set of WIP docs.

### Actual Result
404

### Version
Current

**Comment by levithomason** [comment]
Thanks, repo rename borked it.  Fixing...

**Comment by levithomason** [comment]
Been a little while, how are things? 😄

**Comment by brianespinosa** [comment]
Things are going great. Been MIA due to a massive architectural refactor that is currently underway. I can probably throw my hat into the ring to help with some yarn workspaces stuff in a couple weeks once I am done with some of that work on our end.

We will likely use Stardust under the hood for our component scaffolding. I really like where it's going so far.

Also... now that Stardust is officially going to be it's own thing, how do you feel about me whipping up some logo options? 😄

**Comment by levithomason** [comment]
🔧  Fixed broken docs and broken image paths.

Would be awesome to get more eyes and brains in here.  I'm striving to get our plans back into the open so folks know where things are and what we're thinking next.

I would love some logo ideas!  Here's the piece I was taking for inspiration.  There is way too much detail for this to be a good logo, but I was thinking the concept could be simplified to work at the logo scale and favicon scale.  It may also be a bit typical/expected being a "star" made of "dust".  Again, would love to see more ideas!

<p align=center>
<img width=400 src="https://user-images.githubusercontent.com/5067638/42650476-54e5175a-85c1-11e8-9117-d551f58c1c5d.png" />
</p>

**Comment by brianespinosa** [comment]
I like where you're going with that. I'll take it to email and send you something to look at that is simpler. 👍
