### ISSUE TITLE
Accordion does not hide JSX content when closed

### ISSUE THREAD

**Issue by levithomason** [stardust-ui/react-old#83]
### Steps
1. Open the "Complex content" accordion example.
1. Click the `▼ Pets` title to hide the content.

### Expected Result
The content (list and button) should be hidden.

### Actual Result
The title changes to `▶Pets` which appears closed, however, the content is still shown.

### Version
0.2.0

### Testcase
Use the doc example: https://stardust-ui.github.io/react/components/accordion#variations-list

**Comment by alinais** [comment]
fixed
