### ISSUE TITLE
pxToRem rounding

### ISSUE THREAD

**Issue by mnajdova** [stardust-ui/react-old#92]
### Steps
Use the pxToRem service: pxToRem(32) with default font size of 14px.

### Expected Result
The calculated result in px should be 32.

### Actual Result
The actual calculated result in px is 31.996.

### Version
0.2.0

**Comment by kuzhelov** [comment]
@mnajdova , could you, please, suggest what was the font size detected for your case? Otherwise it is sort of unclear what should be an expected result. Is your default font size configured to be 1px?

**Comment by mnajdova** [comment]
Sorry, the font size was 14px. This came up as an issue in the examples in the docs of the stadust project itself.

**Comment by mnajdova** [comment]
Updated the description in order to be more clear, because the expected and actual results are regarding the pixels, and not the immediate return value of the function.

**Comment by levithomason** [comment]
Does the `31.996px` value result in poor rendering by the browser or other visual anomalies?
